const $=s=>document.querySelector(s);
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let destination=get("sg:lastDestination","");
const news=[["African Union","Continental news and official updates","https://au.int/en/news"],["BBC Africa","Africa news and analysis","https://www.bbc.com/news/world/africa"],["Al Jazeera Africa","African and global current affairs","https://www.aljazeera.com/where/africa/"],["The Conversation Africa","Research-led African perspectives","https://theconversation.com/africa"],["Reuters","International news","https://www.reuters.com/"]];
function renderNews(){const e=$("#newsList");e.innerHTML="";news.forEach(([a,b,u])=>{const x=document.createElement("a");x.className="news";x.href=u;x.target="_blank";x.rel="noopener noreferrer";x.innerHTML=`<b>${a}</b><small>${b}</small>`;e.appendChild(x)})}
function renderBookmarks(){const a=get("sg:bookmarks",[]),e=$("#bookmarkList");e.innerHTML=a.length?"":"<span class='muted'>No bookmarks yet.</span>";a.forEach((x,i)=>{const d=document.createElement("div");d.className="resource";d.innerHTML=`<a href="${x.url}" target="_blank" rel="noopener noreferrer">${x.title||x.url}</a><button data-r="${i}">×</button>`;e.appendChild(d)});e.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{const a=get("sg:bookmarks",[]);a.splice(+b.dataset.r,1);set("sg:bookmarks",a);renderBookmarks()})}
function count(){ $("#historyCount").textContent=get("sg:history",[]).length+" items" }
function openDestination(url){try{const u=new URL(url);if(!/^https?:$/.test(u.protocol))throw 0;destination=u.href;set("sg:lastDestination",destination);const h=get("sg:history",[]).filter(x=>x.url!==destination);h.unshift({url:destination,title:u.hostname,time:Date.now()});set("sg:history",h.slice(0,50));$("#homeView").classList.add("hidden");$("#webView").classList.remove("hidden");$("#destinationTitle").textContent=u.hostname;$("#destinationText").textContent=destination;$("#pageStatus").textContent="Ready • "+u.protocol.replace(":","").toUpperCase();$("#addressInput").value=destination;count()}catch{alert("Only http:// and https:// addresses are supported.")}}
function search(q){q=q.trim();if(!q)return;let u;if(/^https?:\/\//i.test(q))u=q;else if(/^[\w.-]+\.[a-z]{2,}(\/.*)?$/i.test(q))u="https://"+q;else u=$("#engineSelect").value+encodeURIComponent(q);openDestination(u)}
function home(){$("#webView").classList.add("hidden");$("#homeView").classList.remove("hidden");$("#addressInput").value=""}
function external(){if(destination)window.open(destination,"_blank","noopener,noreferrer")}
$("#addressForm").onsubmit=e=>{e.preventDefault();search($("#addressInput").value)};
$("#heroSearch").onsubmit=e=>{e.preventDefault();search($("#heroInput").value)};
document.querySelectorAll("[data-url]").forEach(b=>b.onclick=()=>openDestination(b.dataset.url));
$("#destinationOpen").onclick=external;$("#openExternal").onclick=external;$("#reloadBtn").onclick=()=>destination?openDestination(destination):location.reload();$("#backBtn").onclick=()=>history.back();$("#forwardBtn").onclick=()=>history.forward();
$("#menuBtn").onclick=()=>{$("#sideMenu").classList.add("open");$("#scrim").classList.remove("hidden")};$("#closeMenu").onclick=$("#scrim").onclick=()=>{$("#sideMenu").classList.remove("open");$("#scrim").classList.add("hidden")};
$("#settingsBtn").onclick=()=>$("#settingsDialog").showModal();$("#refreshNews").onclick=renderNews;$("#addBookmark").onclick=()=>{if(!destination)return alert("Open a destination first.");const a=get("sg:bookmarks",[]);if(!a.some(x=>x.url===destination)){a.unshift({url:destination,title:new URL(destination).hostname});set("sg:bookmarks",a.slice(0,50));renderBookmarks()}};
$("#clearData").onclick=()=>{if(confirm("Clear local history and bookmarks?")){localStorage.removeItem("sg:history");localStorage.removeItem("sg:bookmarks");renderBookmarks();count()}};
document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{const a=b.dataset.action;$("#sideMenu").classList.remove("open");$("#scrim").classList.add("hidden");if(a==="home")home();if(a==="bookmarks")$("#bookmarkList").scrollIntoView({behavior:"smooth"});if(a==="history")alert(JSON.stringify(get("sg:history",[]),null,2)||"No history");if(a==="settings")$("#settingsDialog").showModal()});
$("#language").value=get("sg:language","en");$("#adsToggle").checked=get("sg:ads",true);$("#trackersToggle").checked=get("sg:trackers",true);$("#cookieToggle").checked=get("sg:cookies",true);
$("#saveSettings").onclick=()=>{set("sg:language",$("#language").value);set("sg:ads",$("#adsToggle").checked);set("sg:trackers",$("#trackersToggle").checked);set("sg:cookies",$("#cookieToggle").checked)};
renderNews();renderBookmarks();count();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
